version: '3.9'  # Docker Compose version being used
name: my-stack  # name of the Docker stack

services:
  nodejs-service:  # Service named 'nodejs-app'
    container_name: nodejs-app-container  # Custom name for the app container
    restart: always  # Restart policy for the app container
    build:   # Location of the Dockerfile for building the app container
      context: .
      dockerfile: Dockerfile.prod  # Specify the custom Dockerfile name
    ports:  # Ports to expose for the app container
      - '3001:3000'  # Map port 3000 of the container to port 3001 on the host
    volumes: #  volume to persist data outside the container
      - .:/my-app-workdir
    networks: 
      - ja3fer-network  # Connect the app service to the network  
    
  mongodb-service:  # Service named 'mongodb'
    container_name: mongodb-container  # Custom name for the mongodb container
    image: mongo  # Docker image to be used for the mongodb container
    ports:  # Ports to expose for the mongodb container
      - '27030:27017'  # Map port 27017 of the container to port 27018 on the host
    volumes: #  volume to persist data outside the container
      - ja3fer-db-volume:/data/db  # Map the MongoDB data directory to a directory on the host machine
    networks: 
      - ja3fer-network  # Connect the mongodb service to the network


networks:
  ja3fer-network:  # Declaration of the 'docker-workshop-network' network
    driver: bridge  # Specify the driver for the network


volumes:
  ja3fer-db-volume:  # Declaration of the 'db' volume